import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { commandToString, formatDuration, formatExitCode } from "./format.js";
import { sanitizeLog, truncateText, uniqueStrings } from "./sanitize.js";
import type { JsonReport, ReportInput, ReportLog } from "./types.js";

const MAX_FULL_LOG_CHARS = 2_000_000;

export function buildJsonReport(input: ReportInput): JsonReport {
  return {
    schemaVersion: "1.0.0",
    generatedAt: input.generatedAt,
    mode: input.mode,
    cwd: input.cwd,
    command: input.command ?? null,
    logFile: input.logFile ?? null,
    exitCode: input.exitCode,
    durationMs: input.durationMs,
    framework: input.framework,
    failures: input.extraction,
    environment: input.environment,
    log: prepareLog(input.rawLog, input.maxLogChars, input.includeFullLog)
  };
}

export function buildMarkdownReport(input: ReportInput): string {
  const report = buildJsonReport(input);
  const command = report.command ? commandToString(report.command) : null;
  const summaryItems = uniqueStrings(
    [
      ...report.failures.assertionMessages.slice(0, 8),
      ...report.failures.summaryLines.slice(0, 8),
      ...report.failures.fileReferences.slice(0, 8)
    ],
    16
  );

  const lines: string[] = [];
  lines.push("# Failure Report", "");
  lines.push(`Generated: ${report.generatedAt}`, "");
  lines.push("## Status", "");
  lines.push("| Field | Value |");
  lines.push("| --- | --- |");
  lines.push(`| Mode | ${escapeTable(report.mode)} |`);
  lines.push(`| Framework | ${escapeTable(`${report.framework.name} (${report.framework.confidence})`)} |`);
  lines.push(`| Command | ${escapeTable(command ? `\`${command}\`` : "not captured")} |`);
  lines.push(`| Log file | ${escapeTable(report.logFile ?? "not used")} |`);
  lines.push(`| Exit code | ${escapeTable(formatExitCode(report.exitCode))} |`);
  lines.push(`| Duration | ${escapeTable(formatDuration(report.durationMs))} |`);
  lines.push(`| Working directory | ${escapeTable(report.cwd)} |`);
  lines.push("");

  lines.push("## Failure Summary", "");
  if (summaryItems.length === 0) {
    lines.push("- No focused failure summary was extracted. Review the log excerpt below.");
  } else {
    for (const item of summaryItems) {
      lines.push(`- ${inlineCode(item)}`);
    }
  }
  lines.push("");

  lines.push("## Likely Failing Files", "");
  if (report.failures.fileReferences.length === 0) {
    lines.push("- None detected.");
  } else {
    for (const ref of report.failures.fileReferences.slice(0, 25)) {
      lines.push(`- ${inlineCode(ref)}`);
    }
  }
  lines.push("");

  lines.push("## Failure Details", "");
  if (report.failures.blocks.length === 0) {
    lines.push("No failure blocks were extracted.");
  } else {
    report.failures.blocks.forEach((block, index) => {
      lines.push(`### ${index + 1}. ${block.title}`, "");
      lines.push(`Lines: ${block.startLine}-${block.endLine}`, "");
      lines.push(fence(block.text), "");
    });
  }
  lines.push("");

  if (report.failures.stackTraces.length > 0) {
    lines.push("## Stack Traces", "");
    report.failures.stackTraces.slice(0, 5).forEach((trace, index) => {
      lines.push(`### Trace ${index + 1}`, "");
      lines.push(fence(trace), "");
    });
  }

  lines.push("## Environment", "");
  lines.push("| Field | Value |");
  lines.push("| --- | --- |");
  lines.push(`| Platform | ${escapeTable(`${report.environment.platform} ${report.environment.arch}`)} |`);
  lines.push(`| Node | ${escapeTable(report.environment.nodeVersion)} |`);
  lines.push(`| npm | ${escapeTable(report.environment.npmVersion ?? "not available")} |`);
  lines.push(`| Package manager | ${escapeTable(report.environment.packageManager ?? "not detected")} |`);
  if (report.environment.git) {
    lines.push(`| Git branch | ${escapeTable(report.environment.git.branch ?? "detached or unknown")} |`);
    lines.push(`| Git SHA | ${escapeTable(report.environment.git.sha ?? "unknown")} |`);
    lines.push(`| Git status | ${escapeTable(formatGitStatus(report.environment.git.statusSummary))} |`);
  } else {
    lines.push("| Git | not available |");
  }
  lines.push("");

  if (report.environment.git?.changedFiles.length) {
    lines.push("### Changed Files", "");
    for (const file of report.environment.git.changedFiles.slice(0, 50)) {
      lines.push(`- ${inlineCode(file)}`);
    }
    lines.push("");
  }

  lines.push(report.log.included === "full" ? "## Full Log" : "## Log Excerpt", "");
  if (report.log.truncated) {
    lines.push(`Log was truncated from ${report.log.originalChars} characters.`, "");
  }
  lines.push(fence(report.log.text || "No log output captured."), "");
  lines.push("_Generated by failure-packager._", "");

  return lines.join("\n");
}

export async function writeTextFile(filePath: string, content: string): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content, "utf8");
}

export function prepareLog(rawLog: string, maxLogChars: number, includeFullLog: boolean): ReportLog {
  const sanitized = sanitizeLog(rawLog);
  const limit = includeFullLog ? MAX_FULL_LOG_CHARS : maxLogChars;
  const truncated = truncateText(sanitized, limit, {
    fromEnd: !includeFullLog,
    marker: includeFullLog
      ? "[failure-packager: full log exceeded safety cap and was truncated]"
      : "[failure-packager: log excerpt starts here; earlier output omitted]"
  });

  return {
    included: includeFullLog ? "full" : "excerpt",
    text: truncated.text,
    truncated: truncated.truncated,
    originalChars: truncated.originalChars
  };
}

function inlineCode(value: string): string {
  return `\`${value.replace(/`/g, "\\`")}\``;
}

function fence(value: string): string {
  const fenceMarker = value.includes("```") ? "````" : "```";
  return `${fenceMarker}text\n${value}\n${fenceMarker}`;
}

function escapeTable(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function formatGitStatus(summary: {
  clean: boolean;
  changed: number;
  modified: number;
  added: number;
  deleted: number;
  renamed: number;
  untracked: number;
}): string {
  if (summary.clean) {
    return "clean";
  }

  const parts = [
    ["changed", summary.changed],
    ["modified", summary.modified],
    ["added", summary.added],
    ["deleted", summary.deleted],
    ["renamed", summary.renamed],
    ["untracked", summary.untracked]
  ]
    .filter(([, count]) => Number(count) > 0)
    .map(([label, count]) => `${count} ${label}`);

  return parts.join(", ");
}
